package com.charlesmuchogo.research.presentation.instructions


const val FIRST_HEADING = "JINSI YA KUTUMIA ORAQUICK®, KIPIMA Virusi Vya Ukimwi, VVU, CHA KIBINAFSI"
val sentence1 = "Ngojea Soma"
val sentence2 = "Dakika 20"
val sentence3 = "WACHA KIFAA NDANI YA KICHUPA kwa DAKIKA 20 kabla ya kusoma Tokeo. USISOME tokeo baada ya dakika 40."
val sentence4 = "KUTAFSIRI MATOKEO"
val sentence5 = "Somea matokeo ya vipimo kwenye eneo lenye mwangaza mzuri."
val sentence6 = "Kalisha kichupa ndani ya Kikalio."
val sentence7 = "TOKEO CHANYA"
val sentence8 = "Laini mbili kamili, hata ingawa laini ni hafifu, inamaanisha huenda ukawa na virusi vya ukimwi na unahitaji vipimo zaidi."
val sentence9 = "Kwa haraka iwezekanavyo..."
val sentence10 = "Tembelea kituo cha VCT au kituo cha Afya kilicho karibu nawe."
val sentence11 = "LIKISOMWA KABLA YA DAKIKA 20, TOKEO HUENDA LISIWE SAHIHI."
val sentence12 = "TOKEO HASI"
val sentence13 = "MSITARI MMOJA kwenye eneo “C” na HAKUNA msitari kwenye eneo “T”, tokeo lako ni Hasi, Huna Virusi Vya Ukimwi, VVU."
val sentence14 = "Zingatia upimaji wa mara kwa mara. Ukihisi uliambukizwa Virusi Vya Ukimwi, VVU hivi karibuni, fanya upimaji tena baada ya miezi mitatu."
val sentence15 = "TOKEO LISILO KUBALIKA"
val sentence16 = "Hakuna msitari kwenye eneo “C” (hata kukiwa na msitari kwenye eneo “T”), ama kuweko kwa rangi nyekundu inayozuia kusoma tokeo, kipimo hicho si sahihi, kinapaswa kirudiwe. Itakubidi ujipatie pakiti mpya."
val sentence17 = "Kipimo hakikufanya kazi vyema. Tembelea kituo cha VCT au kituo cha Afya kilicho karibu nawe upate upimaji zaidi."
val sentence18 = "Tembelea kituo cha VCT au kituo cha Afya kilicho karibu nawe upate upimaji zaidi."
val sentence19 = "HAKUNA UHAKIKA WA TOKEO"
val sentence20 = "KUTUPA KWA MAELEKEZO ZAIDI, REJEA MWONGOZO WA MAAGIZO UNAOAMBATANA NA VITI VYA KUJARIBU."


val sentence21 = "Kipima Virusi chako kina pakiti mbili zilizo unganishwa."
val sentence22 = "Rarua pakiti upande wenye mchoro wa Kichupa, kisha toa kichupa."
val sentence23 = "Toa kizibo/kifuniko cha kichupa. USIMWAGE maji. USINYWE."
val sentence24 = "Finyilia utambi wa Kifaa juu ya ufizi, pangusa ufizi wote wa juu mara moja na pia ufizi wote wa chini mara moja."
val sentence25 = "Ingiza Kifaa ndani ya kichupa hadi Utambi utumbukie ndani ya maji."
val sentence26 = "Toboa pochi lililo na kifaa cha kipimo na uondoe. USIGUSE pedi bapa kwa vidole vyako. USILE wala kumeza kihifadhi."
