name: Build and Upload Android App to Firebase Distribution

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Fetch packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APPID}}
          token: ${{secrets.TOKEN}}
          groups: beta
          file: build/app/outputs/apk/release/app-release.apk
